jobs:
  integration-build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        ref: integration-build
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.9.6
    - continue-on-error: true
      name: Run tests and build product
      run: 'cp .github/toolchains.xml ~/.m2/toolchains.xml

        xvfb-run mvn -V clean verify -P tests,product

        '
    - continue-on-error: true
      name: Today's date
      run: 'echo "DATE=$(date +''%Y-%m-%d'')" >> $GITHUB_ENV

        '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Deploy to release
      uses: xresloader/upload-to-github-release@v1
      with:
        file: com.archimatetool.editor.product/target/products/Archi-*.*
        overwrite: true
        prerelease: true
        tag_name: integration-build-${{ env.DATE }}
name: Archi Product Integration Build
on:
  repository_dispatch:
    types: trigger-ga___integration-build.yml
